apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.json: |
    {
      "app": {
        "name": "Circle Core",
        "environment": "base",
        "debug": false,
        "log_level": "INFO",
        "api": {
          "host": "0.0.0.0",
          "port": 8000,
          "workers": 2
        }
      },
      "security": {
        "encryption": {
          "algorithm": "AES-GCM",
          "key_rotation_days": 60
        },
        "authentication": {
          "session_timeout_minutes": 30,
          "mfa_enabled": true,
          "password_policy": {
            "min_length": 10,
            "require_uppercase": true,
            "require_lowercase": true,
            "require_numbers": true,
            "require_special": true
          }
        },
        "audit": {
          "enabled": true,
          "retention_days": 90
        }
      },
      "storage": {
        "backend": "file",
        "path": "/data/storage",
        "encryption_enabled": true
      },
      "database": {
        "type": "postgres",
        "host": "postgres",
        "port": 5432,
        "name": "circlecore",
        "user": "circle",
        "pool_size": 10
      },
      "cache": {
        "type": "redis",
        "host": "redis",
        "port": 6379,
        "ttl_seconds": 600
      }
    }
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'circle-core'
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
          - targets: ['circle-core:8000']
