apiVersion: v1
kind: ConfigMap
metadata:
  name: circle-core-config
  labels:
    app: circle-core
data:
  # Configuration for the Circle Core application
  config.json: |
    {
      "app": {
        "name": "Circle Core",
        "environment": "${CIRCLE_ENV}",
        "debug": false,
        "log_level": "INFO",
        "api": {
          "host": "0.0.0.0",
          "port": 8000,
          "workers": 4
        }
      },
      "security": {
        "encryption": {
          "algorithm": "AES-GCM",
          "key_rotation_days": 30
        },
        "authentication": {
          "session_timeout_minutes": 15,
          "mfa_enabled": true,
          "password_policy": {
            "min_length": 12,
            "require_uppercase": true,
            "require_lowercase": true,
            "require_numbers": true,
            "require_special": true,
            "max_age_days": 90
          }
        },
        "audit": {
          "enabled": true,
          "retention_days": 365
        }
      },
      "storage": {
        "backend": "file",
        "path": "/data/storage",
        "encryption_enabled": true
      },
      "database": {
        "type": "postgres",
        "host": "${DB_HOST}",
        "port": ${DB_PORT},
        "name": "${DB_NAME}",
        "user": "${DB_USER}",
        "pool_size": 20,
        "ssl_enabled": true
      },
      "cache": {
        "type": "redis",
        "host": "${REDIS_HOST}",
        "port": ${REDIS_PORT},
        "ttl_seconds": 1200
      }
    }
  
  # Prometheus configuration
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'circle-core'
        static_configs:
          - targets: ['circle-core:8000']
        metrics_path: /metrics
  
  # Default environment variables
  env.properties: |
    CIRCLE_LOG_LEVEL=INFO
    DB_HOST=postgres
    DB_PORT=5432
    DB_NAME=circlecore
    DB_USER=circle
    REDIS_HOST=redis
    REDIS_PORT=6379
