apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: circle-core-ingress
  labels:
    app: circle-core
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
    # TLS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - circle-core.example.com
    secretName: circle-core-tls
  rules:
  - host: circle-core.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: circle-core-service
            port:
              number: 8000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: circle-core-service
            port:
              number: 8000
