apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: circle-core-pvc
  labels:
    app: circle-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
