apiVersion: v1
kind: Secret
metadata:
  name: circle-core-secrets
  labels:
    app: circle-core
type: Opaque
# Note: In a real deployment, do not check in actual secret values
# Use Kubernetes secret management tools or a secure vault (e.g., HashiCorp Vault)
# The values below are placeholders and should be replaced in actual deployments
data:
  # These are base64 encoded placeholder values
  # For production, generate secure random values and encode them
  DB_PASSWORD: cGxhY2Vob2xkZXJfcGFzc3dvcmQ= # "placeholder_password" in base64
  REDIS_PASSWORD: cGxhY2Vob2xkZXJfcGFzc3dvcmQ= # "placeholder_password" in base64
  CIRCLE_ENCRYPTION_KEY: cGxhY2Vob2xkZXJfZW5jcnlwdGlvbl9rZXk= # "placeholder_encryption_key" in base64
  JWT_SECRET: cGxhY2Vob2xkZXJfand0X3NlY3JldA== # "placeholder_jwt_secret" in base64
