apiVersion: v1
kind: Secret
metadata:
  name: circle-core-secrets
  labels:
    app: circle-core
type: Opaque
# NOTE: This is a template. DO NOT store actual secrets in version control.
# The values will be populated by the deployment script.
data:
  # Base64 encoded values (sample values - DO NOT USE IN PRODUCTION)
  # echo -n "value" | base64
  POSTGRES_PASSWORD: UGFzc3dvcmQxMjM= # Password123
  POSTGRES_USER: Y2lyY2xl # circle
  REDIS_PASSWORD: UmVkaXNQYXNzd29yZDEyMw== # RedisPassword123
  CIRCLE_ENCRYPTION_KEY: UDV5S29VMVlzbjVhR1pHTE5vM2hGM2lJa1pzSkRqMFdVbWR0NEx2am41awo= # Random key
